[build]
  command = "npm run build"
  publish = ".next"
  functions = ".netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  # Configure secrets scanning to ignore server-side build outputs where API keys are expected
  SECRETS_SCAN_OMIT_PATHS = ".next/**,.netlify/**,node_modules/**"
  # Explicitly ignore server-side API keys that should be in server code
  SECRETS_SCAN_OMIT_KEYS = "STRIPE_SECRET_KEY,CLERK_SECRET_KEY,SUPABASE_SERVICE_ROLE_KEY"

# Handle Next.js API routes as Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# PDF file headers for optimal viewing
[[headers]]
  for = "/cheat-sheets/**/*.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Content-Disposition = "inline"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Range, Content-Type"
    Cache-Control = "public, max-age=86400"
    Accept-Ranges = "bytes"
    X-Frame-Options = "SAMEORIGIN"

# Static asset caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# General static asset caching
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Security headers (allow same-origin frames for PDF viewing)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[functions]
  directory = ".netlify/functions"
  node_bundler = "esbuild"
